version: "3.8"
services:
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: Dockerfile
    image: discovery-service:latest
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge