version: "3.8"
services:
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: Dockerfile
    image: discovery-service:latest
    ports:
      - "8761:8761"
    networks:
      - chat-bot-test-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  chat-bot-test-network:
    name: chat-bot-test-network
    driver: bridge